[WIP] report: concept for html report feature (needs design)
nodesource/ncm-cli pull request #183
Opened 2019-08-13 02:50 UTC by mster

**Description:**
Allows for users to generate and export a NCM project report in HTML (as per customer request).
- Report contains project information similar to the `--long` report.
- Users can specify the location and filename when exporting via `--html path/to/report.html` (default exports to cwd with a timestamped report name).

**TODO:**
- [ ] Determine & implement design

**Screenshot(s):** *a very ugly duckling*
![Screen Shot 2019-08-12 at 7 48 19 PM](https://user-images.githubusercontent.com/15038724/62911728-3f581200-bd3a-11e9-8ed1-0e9c6b941927.png)

2019-08-14 14:27 UTC, edsadr requested changes
There are two significant things to refactor:

- The logic generating the HTML report is a bit hard to follow, I think an approach of having a single function putting the required variables inside a unique Html template would be better, as the SVG template in the console here: https://github.com/nodesource/nsolid-console-ng/blob/master/lib/svg-template.js. This would be easier to maintain; lets split the template and the logic to create it in different files to create a separation of concerns.

- Remove any third-party dependencies for the CSS and JS embedded in the template, we want a report that could be used offline, also a whole framework is kind of an overkill for what we need here.

2019-08-14 14:27 UTC, edsadr commented on lib/report/html.js
> +  if (output === true) output = path.join(process.cwd(), `ncm-report-${Date.now()}.html`)
Would be nice to include the name of the app in the name

2019-08-19 20:09 UTC, mster commented
Changes completed as per your review @edsadr

2019-08-19 20:10 UTC, mster commented
Updated Example Screenshot:
![bad-package-report](https://user-images.githubusercontent.com/15038724/63295898-ad449200-c282-11e9-8c8a-3b1d3506dd87.png)

2019-08-29 21:15 UTC, edsadr requested changes
The report is working, great work on this @mster, just some items to consider:

- Currently, the report contains different information than the one being generated by the CLI, this could confuse the customer. let's use the same information and also support all filters like `--filter=compliance`

- I know I suggested not to include external assets, but let's add the styles to use our fonts, if the customer has it it will render properly, if not fall back to another font, ask @pdevay about it.

2019-08-30 03:40 UTC, mster commented
Filtering now supported.

![report-c](https://user-images.githubusercontent.com/15038724/63991508-01c6e900-ca9d-11e9-8552-0bcaf146a404.png)

![report-s](https://user-images.githubusercontent.com/15038724/63991467-e065fd00-ca9c-11e9-8c56-1eda41830399.png)

(and depending on security vulnerability level, as the cli does)

2019-08-30 18:41 UTC, mster commented
Reflection of changes

![report3](https://user-images.githubusercontent.com/15038724/64044208-1cd83e00-cb1b-11e9-8fff-2af2801b63d4.png)

2026-09-22 22:46 UTC, closed without merging